apiVersion: v1
appVersion: v2.0.0
description: Responsible for gathering logs and sending them to Loki
engine: gotpl
home: https://grafana.com/loki
icon: https://raw.githubusercontent.com/grafana/loki/master/docs/sources/logo.png
kubeVersion: ^1.10.0-0
maintainers:
- email: lokiproject@googlegroups.com
  name: Loki Maintainers
name: promtail
sources:
- https://github.com/grafana/loki
version: 2.0.1
